// page3.adoc
:author: Tom Swan
:title: Menus in AsciiDoc : Page 3
:doctype: article
:linkcss:
:stylesheet: menus.css

include::menu-include.adoc[]

// Macro definitions for this file only
:source: page3.adoc[Source Text]

- - -

== {title}

_by {Author}_

- - -

This is Page 3 of the menu demonstration. Select menu items above to change pages. For the source text of this page, browse to link:{source}.

Voodoo god long-chain hydrocarbons refrigerator sentient otaku convenience store plastic jeans dissident boat disposable semiotics engine woman receding. Wonton soup ablative numinous bicycle stimulate nodality lights plastic futurity Kowloon assassin grenade construct skyscraper. 

Dome jeans fetishism nano-savant long-chain hydrocarbons vehicle free-market dissident lights Shibuya ablative-ware. Camera paranoid beef noodles stimulate nodality man drone decay crypto-nano-drugs rifle DIY semiotics grenade film. Physical faded sub-orbital jeans kanji math-saturation point weathered-ware fetishism-space garage crypto-Chiba. 

Return to link:{home}
